165 screen responsivity
GraphFilter/GraphFilter pull request #174
Opened 2022-11-07 21:39 UTC by rosaigor138

Closes #165

2022-11-08 13:12 UTC, atilaajones requested changes
- [ ] The screen Project Window is locked to maximization. It's important that this window starts maximized and allow the user to change it.
- [ ] Insert minimize button on Wizartd screen also.
- [x] It is also necessary to test on MAC.

2022-11-08 18:14 UTC, LBeghini requested changes
The following function is repeated 3 times for every window, it should not happen. It should be moved to a place where every window can access it, but then comes the second problem.

The function to calculate the sizes of the windows should be generic. It means that given a scenario where the window width and height has a proper size for a screen with dimensions x and y, width and height should **matematically** calculate the new dimensions (based on the new x and y).

https://github.com/GraphFilter/GraphFilter/blob/7b22b39509f768a7ccf04b9ffe8460e0597f2a85/source/view/wizard/wizard_window.py#L46-L59

2022-11-14 07:48 UTC, LBeghini requested changes
The function is still redeclared for every window. It should be a function that receives each window specific parameters and generically calculates what the screen dimensions should be. Preferably declared in an outer scope, like the `utils` folder, for example, and imported on each window.

2022-11-23 13:12 UTC, LBeghini approved these changes

2022-11-23 20:13 UTC, atilaajones approved these changes

2022-11-23 20:14 UTC, merged