Fix minimization error
GraphFilter/GraphFilter pull request #206
Opened 2022-12-01 21:01 UTC by rosaigor138

Closes #205

2022-12-01 21:10 UTC, LBeghini approved these changes

2022-12-01 22:19 UTC, fsoupimenta approved these changes

2022-12-02 11:58 UTC, LBeghini requested changes
Tested with:
- **System**:  MacOS Ventura 13.0
- **Chip**: M1
- **Python Version**: 3.9.6

At first, minimization worked fine. No errors, minimized and maximized again.
However, when I click the "Help" button, it crashes with the following error:

```
Traceback (most recent call last):
  File "/Users/laviniabeghinidecastro/Documents/GitHub/GraphFilter/source/controller/wizard_controller.py", line 146, in open_message_box
    message_box = MessageBox(text)
  File "/Users/laviniabeghinidecastro/Documents/GitHub/GraphFilter/source/view/components/message_box.py", line 13, in __init__
    self.setText(text)
TypeError: setText(self, str): argument 1 has unexpected type 'bool'
[1]    22311 abort      python app.py
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

2022-12-02 12:10 UTC, LBeghini approved these changes
I figure that the previously mentioned error is happening even in the main branch. I will open an specific issue to address this bug.

2022-12-02 13:54 UTC, atilaajones approved these changes

2022-12-06 22:59 UTC, merged