220 help button graph editing features
GraphFilter/GraphFilter pull request #229
Opened 2023-01-28 15:33 UTC by fsoupimenta

Closes #220

2023-01-28 16:31 UTC, atilaajones requested changes
We can imporove the layout of the text. I suggest try to design a table, with two columns: Keymap and function.

Look this site: [Table generator](https://www.tablesgenerator.com/html_tables)

2023-01-28 18:05 UTC, atilaajones requested changes
The table inserted was using pyqt5, which is not ideal. It allows selection (image attached) and a visual that gives the feeling that it has functionality in the window.

I think it's enough just a text table in html. This table you can generate by [table generator](https://www.tablesgenerator.com)

OBS: I think the "graph editing features" text could be closer to the button.

![image](https://user-images.githubusercontent.com/41593241/215283533-04bd3999-a5ec-4b4f-bc8f-0dec05db175c.png)

2023-01-28 19:11 UTC, fsoupimenta commented
I solved these "selection" problems and also removed the column with the row numbering, but i cannot change the headers style.

Regarding the spacing of the "Graph editing features" label on the toolbar, the spacing logic has to be changed

2023-01-30 19:45 UTC, atilaajones approved these changes

2023-02-02 01:00 UTC, rosaigor138 approved these changes

2023-02-08 17:04 UTC, merged