Blank project option
GraphFilter/GraphFilter pull request #292
Opened 2023-05-03 21:21 UTC by rosaigor138

Closes #261

2023-05-04 17:17 UTC, atilaajones requested changes

2023-05-04 17:17 UTC, atilaajones commented on source/controller/controller.py
>      def start_filter(self):
rename `finish_filter` to `start_project`
rename `start_filter` to `finish_wizard`

2023-05-04 17:17 UTC, atilaajones commented on source/controller/controller.py
> +            create_g6_file(project_information_store.project_location+"/"+project_information_store.project_name+".g6", nx.to_graph6_bytes(graph, header=False).decode('utf-8'))
Format long lines.

2023-05-10 22:12 UTC, rosaigor138 commented on source/controller/controller.py
> +            graph = nx.Graph()
Can be done one method who does all that in utils, but I dont think it's necessary

2023-05-10 22:41 UTC, atilaajones commented on source/controller/controller.py
> +            graph = nx.Graph()
It's not really be necessary, it is for organization. Even the operations that @fsoupimenta did, I order to remove ` Operations` from `Controller` and move function to `Store`.

I think that in the future, a simple adaptation can be made and use the `EmptyGraph(NewGraphStore)` function itself in the `new_graph_store`.

2023-05-10 22:43 UTC, atilaajones approved these changes

2023-05-10 22:51 UTC, merged