Update welcome window version
GraphFilter/GraphFilter pull request #423
Opened 2023-10-22 21:42 UTC by fsoupimenta

Closes #401

2023-10-22 21:46 UTC, atilaajones requested changes
Its necessary to update about window.

2023-10-22 21:50 UTC, fsoupimenta commented
> Its necessary to update about window.

Done!

2023-10-22 21:56 UTC, atilaajones approved these changes

2023-10-23 23:40 UTC, LBeghini approved these changes

2023-10-23 23:41 UTC, merged