Invalid Graph on Combobox
GraphFilter/GraphFilter pull request #442
Opened 2023-11-09 18:35 UTC by rosaigor138

2023-11-15 14:53 UTC, atilaajones commented
You should include the issue number in the description. This way we'll do a review to understand the motivation behind the update. Also try to be more specific in the commit name, not just "fixed"

2023-11-15 15:00 UTC, atilaajones requested changes
This change solved the problem. But I think you should also change the source of the problem: filtering should not return a file with a blank last line. The same goes for inserting the usual new graph, which also inserts a blank line.

2023-11-15 16:39 UTC, LBeghini commented
> This change solved the problem. But I think you should also change the source of the problem: filtering should not return a file with a blank last line. The same goes for inserting the usual new graph, which also inserts a blank line.

@atilaajones the blank line after filtering was an strategy proposed to fix the issue #397 . We can see the changes on the PR #403

2023-11-16 11:48 UTC, fsoupimenta commented
I have two observations about this PR:

1. On `Linux` (more precisely on Ubuntu 22.04.3 LTS) when a file with a blank line at the end is opened, the software already reads this line and throws it into the combobox, leaving the graph invalid. It's worth noting that this behavior only occurs on `Linux`.
2. When you click on an invalid graph in the combobox, the graph counter decreases, leaving duplicates. This behavior probably comes from solving #408 (we can see the changes on #412). An issue will be opened to resolve this bug

2023-11-19 22:04 UTC, atilaajones commented
Test the reported behavior, then try to solve it in PR #444

2023-11-22 18:39 UTC, rosaigor138 commented
> Test the reported behavior, then try to solve it in PR #444 @rosaigor138

I don't understand why that I need to make that changes on the change graph file PR

2023-11-22 19:18 UTC, rosaigor138 commented on source/controller/project_controller.py
> +        self.project_tool_bar.combo_graphs.setItemText(index, f'Graph {index+1} - Invalid')
@fsoupimenta  I found the problem, when the invalid graph window was called, the combobox counter was reogarnized, but the index received was from 0 to n-1 unlike how our combobox works.

2023-11-26 06:02 UTC, LBeghini approved these changes
Working on macOS Sonoma version 14.1.1 Chip Apple M1

2023-11-26 06:08 UTC, fsoupimenta requested changes
@rosaigor138 The blank line at the end is still read by the software in ubuntu

2024-05-08 22:44 UTC, atilaajones approved these changes
@fsoupimenta. I think this PR can be merged, right?

2024-07-10 22:51 UTC, closed without merging