Add multiple edges simultaneously
GraphFilter/GraphFilter pull request #457
Opened 2024-04-03 13:41 UTC by fsoupimenta

Closes #453 
Closes #447

2024-04-09 21:15 UTC, fsoupimenta commented
@GraphFilter/version-3-0 

The functionality has been implemented and is available for testing by running the application. 
However, I believe that the responsibility for this issue belongs to the [netgraph ](https://github.com/paulbrodersen/netgraph)library, and not to us. That's why I took the initiative to open an issue in their repository with this request: https://github.com/paulbrodersen/netgraph/issues/88

In addition, during implementation, i identified some bugs that caused the software to fail. To get around these problems, it was necessary to overwrite the `netgraph` method of adding nodes. This reinforces the idea that it is not our responsibility to implement this functionality.

> [!Note]
> While we wait for a response from the netgraph, if you want to test the functionality, simply select several vertices at the same time using `Ctrl + left mouse click and drag`, then press the plus button _`+ or =`_ anywhere on the board.

2024-05-01 18:26 UTC, atilaajones commented
I did the tests.
I observed some unexpected behavior when running the procedure: 

1. Select several vertices using the rectangle with the left mouse button;
2. Insert new vertex;
3. The software slowed down a bit and lost the labels of the new vertices

The same behavior occurred when selecting using the CTRL button.
Please note that the issue [https://github.com/paulbrodersen/netgraph/issues/88](https://github.com/paulbrodersen/netgraph/issues/88) has been answered, so please forward it.

2024-07-10 02:10 UTC, atilaajones requested changes
- Unexpected behavior when inserting a vertex using the + key.
- Vertex is not removed using the DEL key

**Change the help text (?) of the project window:** 
`Insert or + or =: Insert a new node (this will be adjacent to previously selected vertices)`

**Insert a new line of help text:**
`Hold and drag left-click: Select multiple edges and vertices`

2024-07-10 02:34 UTC, LBeghini approved these changes

2024-07-10 02:34 UTC, LBeghini approved these changes

2024-07-10 02:41 UTC, merged